name: "PR Benchmark workflow"
on:
  # Trigger benchmark test on this PR's commit against master.
  pull_request:
jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.9'
      - name: Build go-algorand
        run: scripts/travis/build.sh
      - name: Run benchmark
        run: go test ./data/transactions/logic -benchtime 30s -bench 'BenchmarkUintMath' | tee benchmark_output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: benchmark_output.txt
          # Where the previous data file is stored
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '110%'
          comment-on-alert: true
